;; -*- mode: eask; lexical-binding: t -*-

(package "helm-gtags"
         "1.5.7"
         "GNU GLOBAL helm interface")

(website-url "https://github.com/syohex/emacs-helm-gtags")
(keywords "")

(package-file "helm-gtags.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source "melpa")

(depends-on "emacs" "24.4")
(depends-on "helm")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
